services:
  - type: web
    name: smartwatches-ecommerce
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt && python -c "from app import create_app; from app.extensions import db; app = create_app(); app.app_context().push(); db.create_all()"
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: smartwatches-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false

databases:
  - name: smartwatches-db
    databaseName: smartwatches
    user: smartwatches_user
